// this file is responsible for providing autogenerated snippets
// Language: javascript
// Path: autogenerate.js
const fs = require("fs");
const snippets = {
  "/* DON'T EDIT THIS FILE : This file is autogenerated using autogenerate.js */": true,
};
let files = fs.readdirSync(__dirname + "/src/SallaJson/snippets.twig/");
files.forEach((f) => {
  let name = f.replace(".twig", "");
  snippets[name] = {
    prefix: name,
    body: fs.readFileSync(
      __dirname + "/src/SallaJson/snippets.twig/" + f,
      "utf8"
    ),
    description: name,
    scope: "text.html.twig",
  };
});

fs.writeFileSync(
  __dirname + "/src/snippets/salla.snippets.json",
  JSON.stringify(snippets, null, 2)
);
